name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Release info
        id: release
        run: |
          echo "::set-output name=version::${GITHUB_REF/refs\/tags\//}"
          echo "::set-output name=commit::$(git rev-parse --short HEAD)"
          echo "::set-output name=build_date::$(date +'%Y-%m-%d')"

      - name: Validates GO releaser config
        uses: goreleaser/goreleaser-action@v2
        with:
          args: check

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Token for homebrew-tap repo: https://github.com/k8scat/homebrew-tap
          HOMEBREW_TOKEN: ${{ secrets.HOMEBREW_TOKEN }}

#      - name: Bump formula
#        uses: dawidd6/action-homebrew-bump-formula@v3
#        with:
#          token: ${{ secrets.HOMEBREW_TOKEN }}
#          formula: articli

      # BUILDING MULTI-ARCHITECTURE IMAGES WITH GITHUB ACTIONS: https://blog.oddbit.com/post/2020-09-25-building-multi-architecture-im/
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: k8scat
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: k8scat
          password: ${{ secrets.GITHUB_TOKEN }}
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/k8scat/articli:latest
            ghcr.io/k8scat/articli:${{ steps.release.outputs.version }}
            k8scat/articli:latest
            k8scat/articli:${{ steps.release.outputs.version }}
          platforms: linux/amd64,linux/arm64
          # Multiple build-args: https://github.com/docker/build-push-action/issues/380#issuecomment-855477968
          build-args: |
            "VERSION=${{ steps.release.outputs.version }}"
            "COMMIT=${{ steps.release.outputs.commit }}"
            "BUILD_DATE=${{ steps.release.outputs.build_date }}"

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Publish NPM
        env:
          NPM_USER: k8scat
          NPM_PASS: ${{ secrets.NPM_PASS }}
          NPM_EMAIL: k8scat@gmail.com
        run: |
          sed -i "s/\"version\": \"ci-version\"/\"version\": \"${{ steps.release.outputs.version }}\"/g" package.json
          
          npm install
          npm install -g npm-cli-login
          npm-cli-login
          npm publish --access public
          
          git config --global user.name "K8sCat"
          git config --global user.email "k8scat@gmail.com"
          git add package.json
          git commit -m "Release NPM @k8scat/articli ${{ steps.release.outputs.version }}"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/k8scat/articli.git main
